In [1]:
import numpy as np

## Data type and Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1,2,3.0],
           [4,5,6.2]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
             [[10,11,12],
              [13,14,15],
              [16,17,18]]])

a2


array([[1. , 2. , 3. ],
       [4. , 5. , 6.2]])

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a1.shape

(3,)

In [16]:
a2.shape

(2, 3)

In [17]:
a3.shape

(2, 3, 3)

In [18]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [20]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [21]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [22]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Creating Array

In [23]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [24]:
sample_array.dtype

dtype('int64')

In [25]:
ones = np.ones((2,3))

In [26]:
type(ones)

numpy.ndarray

In [27]:
ones.dtype

dtype('float64')

In [28]:
zeros = np.zeros((2,3))

In [29]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
range_array = np.arange(0,10,2)

In [31]:
range_array

array([0, 2, 4, 6, 8])

In [32]:
random_array = np.random.randint(0, 20, size = (3,5))

In [33]:
random_array

array([[ 2,  7, 15,  3, 19],
       [ 1, 12,  7,  4, 14],
       [ 9, 12,  4,  3, 13]])

In [34]:
random_array.size

15

In [35]:
random_array.shape

(3, 5)

In [38]:
random_array = np.random.random((5,3))

In [39]:
random_array.shape

(5, 3)

In [40]:
random_array_3 = np.random.rand(5, 5, 5)

In [41]:
random_array_3

array([[[0.84141158, 0.80153709, 0.54044692, 0.26925625, 0.68819797],
        [0.75850438, 0.66933391, 0.2184164 , 0.53205705, 0.63971407],
        [0.83727824, 0.66381596, 0.0471768 , 0.00704866, 0.65877508],
        [0.60075872, 0.82828614, 0.80020903, 0.16676195, 0.40717892],
        [0.9775417 , 0.08534975, 0.14440281, 0.21390176, 0.23671362]],

       [[0.60277384, 0.20258654, 0.77419744, 0.64589501, 0.99785034],
        [0.00658507, 0.64789685, 0.11602776, 0.74449058, 0.21650355],
        [0.69199357, 0.09525873, 0.09618169, 0.22737755, 0.18930643],
        [0.38001498, 0.54549388, 0.9487815 , 0.71049978, 0.28355495],
        [0.89328926, 0.52726132, 0.40030169, 0.40818875, 0.39705753]],

       [[0.74399258, 0.20063421, 0.57194392, 0.21877817, 0.41182669],
        [0.9070494 , 0.4361768 , 0.18468202, 0.61980583, 0.45070623],
        [0.68905442, 0.49345251, 0.20635181, 0.3649933 , 0.74613707],
        [0.3611802 , 0.11455901, 0.92362244, 0.07115405, 0.64376747],
        [0.98476

In [46]:
random_array_4 = np.random.randint(0, 20, size = (3,5, 2))
random_array_4

array([[[ 9, 11],
        [ 6,  9],
        [14,  2],
        [ 3, 10],
        [ 2, 17]],

       [[13, 10],
        [11,  5],
        [19,  4],
        [ 6,  7],
        [14,  2]],

       [[ 0, 16],
        [ 0, 15],
        [ 6,  6],
        [ 8, 18],
        [17, 14]]])

In [51]:
# Pseudo random numbers
np.random.seed(seed=9999)
random_array_5 = np.random.randint(10, size=(5,3))
random_array_5

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [54]:
np.random.seed(7)
random_array_6 = np.random.random((5, 3))
random_array_6

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices

In [59]:
np.unique(random_array_5)

array([0, 1, 3, 5, 6, 8, 9])

In [60]:
a1

array([1, 2, 3])

In [61]:
a1[0]

1

In [62]:
a3.shape

(2, 3, 3)

In [63]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [67]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [68]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [69]:
random_array_4.dtype

dtype('int64')

In [70]:
random_array_4.shape

(3, 5, 2)

In [79]:
random_array_4[::-1, ::-1, ::-1]

array([[[14, 17],
        [18,  8],
        [ 6,  6],
        [15,  0],
        [16,  0]],

       [[ 2, 14],
        [ 7,  6],
        [ 4, 19],
        [ 5, 11],
        [10, 13]],

       [[17,  2],
        [10,  3],
        [ 2, 14],
        [ 9,  6],
        [11,  9]]])

In [78]:
random_array_4

array([[[ 9, 11],
        [ 6,  9],
        [14,  2],
        [ 3, 10],
        [ 2, 17]],

       [[13, 10],
        [11,  5],
        [19,  4],
        [ 6,  7],
        [14,  2]],

       [[ 0, 16],
        [ 0, 15],
        [ 6,  6],
        [ 8, 18],
        [17, 14]]])

## Manipulating & Comparing Arrays

### Arithmetic

In [80]:
a1

array([1, 2, 3])

In [81]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [82]:
a1 + ones

array([2., 3., 4.])

In [83]:
a1 - ones

array([0., 1., 2.])

In [84]:
a1 * ones

array([1., 2., 3.])

In [85]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 18.6]])

In [86]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 18.6]])

In [87]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [88]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [89]:
a2 / a1

array([[1.        , 1.        , 1.        ],
       [4.        , 2.5       , 2.06666667]])

In [90]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 38.44]])

In [95]:
np.mod(a3, 2)

array([[[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]]])

In [96]:
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 492.74904109]])

## Aggregation

In [97]:
np.std(a2)

1.7575235101952091

In [98]:
np.var(a2)

3.088888888888889

In [99]:
mat1 = np.random.randint(20, size= (4,3))

In [100]:
mat1

array([[19, 12,  5],
       [16,  0,  2],
       [ 9, 14,  6],
       [ 4, 14,  9]])

In [105]:
mat2 = np.random.randint(50,100, size=(4,3))

In [106]:
mat2

array([[78, 57, 73],
       [60, 91, 85],
       [50, 57, 73],
       [78, 82, 71]])

In [108]:
np.dot(mat1, mat2.T)

array([[2531, 2657, 1999, 2821],
       [1394, 1130,  946, 1390],
       [1938, 2324, 1686, 2276],
       [1767, 2279, 1655, 2099]])

In [118]:
np.random.seed(0)
sales_amount = np.random.randint(5, 20, size=(5,3))

In [111]:
import pandas as pd

In [119]:
sales_amount = pd.DataFrame(sales_amount, index= ["Mon", "Tue", "Wed", "Thu", "Fri"],
                           columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [120]:
sales_amount

Almond Butter  Peanut Butter  Cashew Butter
Mon             17             10              5
Tue              8             16              8
Wed             12             14              8
Thu             10              7              9
Fri             12             11             13

In [122]:
prices = np.array([14, 10, 30])

In [126]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [127]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             14             10             30

In [128]:
total_prices = prices.dot(sales_amount.T)

In [129]:
total_prices

array([488, 512, 548, 480, 668])

In [143]:
sales_amount["Total ($)"] = total_prices.T

In [144]:
sales_amount

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon             17             10              5        488
Tue              8             16              8        512
Wed             12             14              8        548
Thu             10              7              9        480
Fri             12             11             13        668

In [141]:
sales_amount.drop(labels="Total sale amount ($)",axis=1,inplace=True)

In [146]:
sales_amount["Total ($)"] > 500

Mon    False
Tue     True
Wed     True
Thu    False
Fri     True
Name: Total ($), dtype: bool

In [147]:
np.sort(random_array)

array([[0.57124449, 0.60418371, 0.90118836],
       [0.53330273, 0.72693553, 0.83555983],
       [0.59775206, 0.69737025, 0.93980055],
       [0.18266976, 0.2213725 , 0.84935284],
       [0.26184482, 0.36418278, 0.72603777]])

In [148]:
np.argsort(random_array)

array([[0, 2, 1],
       [1, 2, 0],
       [1, 2, 0],
       [0, 2, 1],
       [2, 0, 1]])

In [149]:
a1

array([1, 2, 3])

In [150]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.2]])

In [151]:
sales_amount

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon             17             10              5        488
Tue              8             16              8        512
Wed             12             14              8        548
Thu             10              7              9        480
Fri             12             11             13        668

<img src="original.png" />

In [153]:
# Turn an image into NumPy Array
from matplotlib.image import imread

diagram = imread("original.png")

In [154]:
type(diagram)

numpy.ndarray

In [155]:
diagram.shape

(1296, 3304, 4)

In [157]:
diagram.ndim

3

In [160]:
diagram[:2]

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)